--
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by reese.
--- DateTime: 3/5/2022 12:29 AM
--- Desc: main file for game

-- import statements
import "CoreLibs/object"
import "CoreLibs/graphics"
import "CoreLibs/sprites"
import "CoreLibs/timer"
import "CoreLibs/animation"
import "CoreLibs/save"
import "CoreLibs/ui"
import "CoreLibs/strict"
import "CoreLibs/string"