--
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by reese.
--- DateTime: 3/5/2022 12:29 AM
--- Desc: main file for game

-- import statements
import "CoreLibs/object"
import "CoreLibs/graphics"
import "CoreLibs/sprites"
import "CoreLibs/timer"
import "CoreLibs/animation"
import "CoreLibs/save"
import "CoreLibs/ui"
import "CoreLibs/string"
import "CoreLibs/ui/gridview"

-- graphics const

local gfx <const> = playdate.graphics

-- player sprite

local player = nil

--setup function

function setup()
    local font = playdate.graphics.font.new("assets/img/pulp-font-full-width-table-8-8.png")
    local playerIMG = gfx.image.new("assets/img/player_img")
    assert(playerIMG)

    playdate.ui.crankIndicator:start()
    playdate.ui.crankIndicator:update()

    player = gfx.sprite.new(playerIMG)
    player:moveTo(200, 120)
    player:add()

    --making titlecard and displaying for 3 seconds

    local titleCard = gfx.image.new("assets/img/launchImage.png")

    gfx.sprite.setBackgroundDrawingCallback(
            function( x, y, width, height )
                gfx.setClipRect( x, y, width, height ) -- let's only draw the part of the screen that's dirty
                titleCard:draw( 0, 0 )
                gfx.clearClipRect() -- clear so we don't interfere with drawing that comes after this
            end
    )

    local titleTimer = playdate.timer.new(3000)

    while(titleTimer.value~=0) do

        end



    local background = gfx.image.new("assets/img/bg_img.png")
    assert(background)

    gfx.sprite.setBackgroundDrawingCallback(
            function( x, y, width, height )
                gfx.setClipRect( x, y, width, height ) -- let's only draw the part of the screen that's dirty
                background:draw( 0, 0 )
                gfx.clearClipRect() -- clear so we don't interfere with drawing that comes after this
            end
    )

end

setup()

--update function

function playdate.update()
    if playdate.buttonIsPressed( playdate.kButtonUp ) then
        player:moveBy( 0, -2 )
    end
    if playdate.buttonIsPressed( playdate.kButtonRight ) then
        player:moveBy( 2, 0 )
    end
    if playdate.buttonIsPressed( playdate.kButtonDown ) then
        player:moveBy( 0, 2 )
    end
    if playdate.buttonIsPressed( playdate.kButtonLeft ) then
        player:moveBy( -2, 0 )
    end

    gfx.sprite.update()
    playdate.timer.updateTimers()

end